[package]
name = "smb2-practice-mod"
version = "2.0.0"
edition = "2021"

[dependencies]
arrayvec = { version = "0.7.6", default-features = false }
cty = "0.2.2"
panic-halt = "0.2.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bin]]
name = "smb2-practice-mod"
test = false
bench = false
