[package]
name = "smb2-practice-mod"
version = "2.0.0"
edition = "2021"

[dependencies]
arrayvec = { version = "0.7.6", default-features = false }
critical-section = "1.1.3"
num_enum = { version = "0.7.3", default-features = false }
once_cell = { version = "1.20.2", default-features = false, features = [
    "critical-section",
] }
zerocopy = { version = "0.8.6", features = ["derive"] }

[lib]
crate-type = ["staticlib"]
test = false
bench = false
