name: Build

on:
  push:
    branches: ['master']
    tags: ['*']
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: complexplane/smb2-practice-mod:latest
      options: --user vscode
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: make -j